version: "3.9"
name: ingenero

networks:
    ingenero:

services:

    nginx:
        image: nginx:stable
        volumes: 
            - ./html:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - mysql
        networks:
            - ingenero

    php:
        build: 
            context: .
            dockerfile: ./Dockerfile-php
        volumes: 
            - ./html:/var/www/html
        ports:
            - 9000:9000
        restart: always
        networks:
            - ingenero

    mysql:
        image: mysql:latest
        volumes: 
            - ./mysql:/var/lib/mysql
        ports:
            - 9095:3306
        restart: always
        environment:
            - MYSQL_DATABASE=ingenero
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - ingenero

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD:
        ports:
            - "38001:80"
        restart: always
        networks:
            - ingenero
        depends_on:
            - php
            - mysql